# Script to extract the final responses from the world-logs generated by blender2.0

# Puts each prompt - response per row
from os import dup
from numpy import promote_types
import pandas as pd
from datetime import date
import json
RESPONSE_PATH = "./data_scripts/model_responses/"
PROMPT_PATH = "./data_scripts/prompts/"
FINAL_PATH = "./data_scripts/final_responses/"
dataset_name = "esl"
model_size = "3b"
date_generated = "20220127"
PROMPT_FILE = f"{dataset_name}_blender2{model_size}_{date_generated}.jsonl"

with open(RESPONSE_PATH + PROMPT_FILE) as file:
    responses_list = file.readlines()

responses_list = [json.loads(response)['dialog'][0][-1]['text'].replace('_POTENTIALLY_UNSAFE__','') for response in responses_list]

# Save each json into a line
with open(FINAL_PATH + PROMPT_FILE.split('.')[0]+'.txt', 'w') as file:
    for response in responses_list:
        file.write(response + "\n")

